{{- if .Values.tempo.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: tempo
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  tempo.yaml: |
    server:
      http_listen_port: {{ .Values.tempo.server.http_listen_port }}
      grpc_listen_port: {{ .Values.tempo.server.grpc_listen_port }}
    
    usage_report:
      reporting_enabled: false

    distributor:
      receivers:
        otlp:
          protocols:
            grpc: {}
            http: {}

    metrics_generator:
      storage:
        path: {{ .Values.tempo.metricsGenerator.storagePath | quote }}
      remote_write:
        - url: {{ .Values.tempo.metricsGenerator.remoteWriteUrl | quote }}
      processors:
        - service-graphs
        - span-metrics
        - local-blocks

    ingester:
      trace_idle_period: {{ .Values.tempo.ingester.trace_idle_period }}
      max_block_duration: {{ .Values.tempo.ingester.max_block_duration }}

    compactor:
      compaction:
        block_retention: {{ .Values.tempo.compactor.block_retention }}

    storage:
      trace:
        backend: {{ .Values.tempo.storage.backend }}
        {{ .Values.tempo.storage.backend }}:
          path: {{ .Values.tempo.storage.path }}

    querier:
      frontend_worker:
        frontend_address: {{ .Values.tempo.querier.frontend_address }}

    query_frontend:
      search:
        enabled: {{ .Values.tempo.query_frontend.search_enabled }}
{{- end }}
