apiVersion: v2
name: otel-collector # (Consistent with ArgoCD app_name)
version: 0.1.0           # Your chart's version
appVersion: "0.128.0"    # <--- CORRECTED appVersion based on your 'helm search repo'
description: OpenTelemetry Collector managed by ArgoCD
type: application
home: https://opentelemetry.io/
sources:
  - https://github.com/open-telemetry/opentelemetry-helm-charts
dependencies:
  - name: opentelemetry-collector
    version: "0.127.1"
    repository: "https://open-telemetry.github.io/opentelemetry-helm-charts"