opentelemetry-collector:
  mode: deployment
  image:
    repository: "otel/opentelemetry-collector-contrib"
    tag: "0.128.0"

  config:
    receivers:
      otlp:  # <-- Receives both metrics and traces from instrumented apps (via OTLP gRPC or HTTP)
        protocols:
          grpc: {}  # Enables gRPC protocol (usually port 4317)
          http: {}  # Enables HTTP protocol (usually port 4318)

      hostmetrics:
        collection_interval: 5s
        scrapers:
          cpu:
          memory:
          disk:
          filesystem:
          network:
          load:

    exporters:
      debug:  # <-- Just prints received data to logs (for debug)
        verbosity: detailed

      prometheusremotewrite:
        endpoint: http://thanos-receiver-receive.thanos-ns.svc.cluster.local:19291/api/v1/receive
        tls:
          insecure_skip_verify: true
        resource_to_telemetry_conversion:
          enabled: true
        # <-- Sends metrics to Thanos (no trace support here)

      ##  Add exporter to support tracing to Tempo
      otlp:
        endpoint: tempo-app.monitoring.svc.cluster.local:4317
        tls:
          insecure: true  # <-- For local testing; adjust for prod

    processors:
      batch: {}  # <-- Batches metrics/traces before export

    extensions:
      health_check:
        endpoint: 0.0.0.0:13133
      pprof:
        endpoint: 0.0.0.0:1777
      zpages:
        endpoint: 0.0.0.0:55679

    service:
      telemetry:
        logs:
          level: debug
        metrics:
          address: 0.0.0.0:8888
      extensions:
        - health_check
        - pprof
        - zpages
      pipelines:
        metrics:  # <-- Sends metrics from OTLP & hostmetrics to Thanos
          receivers:
            - otlp
            - hostmetrics  # <-- NEW: Add hostmetrics to pipeline
          processors:
            - batch
          exporters:
            - debug
            - prometheusremotewrite

        traces:  # <-- Pipeline to forward OTLP traces to Tempo
          receivers:
            - otlp
          processors:
            - batch
          exporters:
            - debug
            - otlp
