# kubernetes-gitops-manifests/platform-apps/otel-collector/values.yaml
mode: deployment
image:
  repository: otel/opentelemetry-collector-contrib
  tag: 0.128.0 # This matches the tag from your .tpl file

config:
  receivers:
    otlp:
      protocols:
        grpc: {}
        http: {}

  exporters:
    debug:
      verbosity: detailed
    prometheusremotewrite:
      endpoint: http://thanos-receiver-receive.thanos-ns.svc.cluster.local:19291/api/v1/receive # <-- INJECTED VALUE
      tls:
        insecure_skip_verify: true
      resource_to_telemetry_conversion:
        enabled: true

  processors:
    batch: {}

  extensions:
    health_check:
      endpoint: 0.0.0.0:13133
    pprof:
      endpoint: 0.0.0.0:1777
    zpages:
      endpoint: 0.0.0.0:55679

  service:
    telemetry:
      logs:
        level: debug
      metrics:
        address: 0.0.0.0:8888
    extensions:
      - health_check
      - pprof
      - zpages
    pipelines:
      metrics:
        receivers:
          - otlp
        processors:
          - batch
        exporters:
          - debug
          - prometheusremotewrite