opentelemetry-collector:
  mode: deployment

  image:
    repository: "otel/opentelemetry-collector-contrib"
    tag: "0.128.0"

  config:
    receivers:
      # Receives telemetry data from instrumented apps
      otlp:
        protocols:
          grpc: {}
          http: {}

      # Collect host-level metrics
      hostmetrics:
        collection_interval: 5s
        scrapers:
          cpu:
          memory:
          disk:
          filesystem:
          network:
          load:

    processors:
      # Batches telemetry for efficiency
      batch: {}

      # Converts spans (traces) into RED metrics
      metricsgeneration:  # Required exporter for span RED metrics
        dimensions:
          - name: http.method         # Useful for grouping by HTTP verb
          - name: http.status_code    # Helps with error rate
          - name: service.name        # Groups spans by service

    exporters:
      # Logs all telemetry — useful for debugging
      debug:
        verbosity: detailed

      # Exports metrics to Thanos via remote_write
      prometheusremotewrite:
        endpoint: http://thanos-receiver-receive.thanos-ns.svc.cluster.local:19291/api/v1/receive
        tls:
          insecure_skip_verify: true
        resource_to_telemetry_conversion:
          enabled: true

      # Prometheus exporter — used by spanmetrics processor
      prometheus:
        endpoint: 0.0.0.0:8889  # Span RED metrics exposed here

      # Exports traces to Tempo
      otlp:
        endpoint: tempo-app.monitoring.svc.cluster.local:4317
        tls:
          insecure: true  # OK for local/dev

    extensions:
      health_check:
        endpoint: 0.0.0.0:13133
      pprof:
        endpoint: 0.0.0.0:1777
      zpages:
        endpoint: 0.0.0.0:55679

    service:
      telemetry:
        logs:
          level: debug
        metrics:
          address: 0.0.0.0:8888  # Collector internal metrics (not span RED)
      extensions:
        - health_check
        - pprof
        - zpages
      pipelines:
        # Metrics pipeline for app + host metrics
        metrics:
          receivers:
            - otlp
            - hostmetrics
          processors:
            - batch
          exporters:
            - debug
            - prometheusremotewrite
            - prometheus  # Must include to expose span RED metrics

        # Traces pipeline that feeds RED metrics via spanmetrics processor
        traces:
          receivers:
            - otlp
          processors:
            - metricsgeneration
            - batch
          exporters:
            - debug
            - otlp

  #  This block exposes port 8889 for Prometheus/Thanos to scrape RED metrics
#  service:
#    enabled: true
#    ports:
#      - name: prom-spanmetrics
#        port: 8889
#        targetPort: 8889
