main: # This 'main' key corresponds to the 'alias: main' in your Chart.yaml for the Grafana subchart
  adminUser: "admin"
  adminPassword: "admin" # <--- WARNING: Default password stored in plain text in Git. Not recommended for production!
  # For production, consider using a Kubernetes Secret and referencing it here,
  # or using a secret management solution like Vault.

  # --- Dashboard Provisioning Configuration ---
  # This section enables the Grafana sidecar that watches for dashboard ConfigMaps
  sidecar:
    dashboards:
      enabled: true
      # The 'label' and 'labelValue' here must match what you set in dashboards-configmap.yaml
      label: grafana_dashboard
      labelValue: "1"
      # Uncomment the line below if your dashboard ConfigMaps might be in other namespaces
      # searchNamespace: ALL

  # This section configures Grafana's internal provisioning system
  grafana.ini:
    paths:
      # This is the directory where Grafana expects to find its provisioning configuration files.
      # This is a standard Grafana path and usually doesn't need to be changed.
      provisioning: /etc/grafana/provisioning

    dashboardProviders:
      # The key 'dashboardproviders.yaml' here is the NAME OF THE FILE
      # that Grafana will look for inside its provisioning directory
      # (i.e., /etc/grafana/provisioning/dashboards/dashboardproviders.yaml).
      # This file's content is defined directly below.
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
          - name: 'custom-app-dashboards' # A descriptive name for this dashboard provider
            orgId: 1 # The Grafana organization ID (1 is default)
            folder: 'Application Dashboards' # Optional: Dashboards will appear in this folder in Grafana UI
            type: file # Specifies that dashboards are loaded from files
            disableDeletion: false # Set to 'true' if you want to prevent deletion from Grafana UI
            editable: false # Set to 'false' if you want dashboards to be read-only in Grafana UI
            options:
              # This 'path' is where the Grafana sidecar *mounts* the contents
              # of the ConfigMap created by your dashboards-configmap.yaml template.
              # The official Grafana Helm chart's sidecar typically mounts ConfigMaps
              # with the 'grafana_dashboard: "1"' label to /var/lib/grafana/dashboards.
              path: /var/lib/grafana/dashboards
  # --- END Dashboard Provisioning Configuration ---

  # Datasources configuration (your existing configuration)
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: "http://thanos-query-query.thanos-ns.svc.cluster.local:9090"
          isDefault: true
          access: proxy
          editable: true
        - name: Tempo
          type: tempo
          url: "http://tempo-app.monitoring.svc.cluster.local:3200"
          isDefault: false
          access: proxy
          editable: true
