# thanos-query/templates/servicemonitor.yaml
{{- if .Values.query.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "thanos-query-app.fullname" . }}
  namespace: {{ .Values.query.metrics.serviceMonitor.namespace }}
  labels:
    {{- include "thanos-query-app.labels" . | nindent 4 }}
    {{- with .Values.query.metrics.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: thanos
      app.kubernetes.io/instance: thanos-query
      app.kubernetes.io/component: thanos-query
  endpoints:
  - port: http
    interval: 30s
    path: /metrics
{{- end }}