# Existing top-level config stays as is...

tempo:
  config:
    server:
      http_listen_port: 3100  # internal HTTP port
    distributor:
      receivers:
        otlp:
          protocols:
            grpc:
            http:

  # Explicitly expose port 4317!
  distributor:
    service:
      enabled: true
      ports:
        - name: otlp-grpc
          port: 4317
          targetPort: 4317

    ingester:
      trace_idle_period: 10s
      max_block_duration: 5m
      # NOTE: This block is config for the ingester process itself, not resources

    compactor:
      compaction:
        block_retention: 1h

    storage:
      trace:
        backend: "local"
        local:
          path: "/bitnami/grafana-tempo/data"  # local dev storage

    querier:
      frontend_worker:
        frontend_address: tempo-distributor:9095

    query_frontend:
      search:
        enabled: true

  # Override the global container resources
  containerResources:
    requests:
      memory: 1.5Gi
      cpu: 250m
    limits:
      memory: 2Gi
      cpu: 500m

  # Here we add resource requests and limits for the ingester container (to prevent OOM):
  ingester:
    enabled: true
    resources:
      requests:
        memory: 1.5Gi
        cpu: 250m
      limits:
        memory: 2Gi
        cpu: 500m

# The rest unchanged:

persistence:
  enabled: false

service:
  type: ClusterIP
  ports:
    - name: tempo
      port: 3100
      targetPort: 3100
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
    - name: otlp-http
      port: 4318
      targetPort: 4318

metrics:
  enabled: false

alertmanager:
  enabled: false
grafana:
  enabled: false
prometheus:
  enabled: false
