tempo:
  enabled: true

  service:
    type: ClusterIP
    ports:
      - name: otlp-grpc
        port: 4317
        targetPort: 4317
      - name: otlp-http
        port: 4318
        targetPort: 4318
      - name: tempo
        port: 3200
        targetPort: 3200

  resources:
    requests:
      memory: 1.5Gi
      cpu: 250m
    limits:
      memory: 2Gi
      cpu: 500m

  persistence:
    enabled: false

  metricsGenerator:
    enabled: false

  # These are used by the ConfigMap template
  server:
    http_listen_port: 3200
    grpc_listen_port: 9095

  ingester:
    trace_idle_period: "10s"
    max_block_duration: "5m"

  compactor:
    block_retention: "1h"

  storage:
    backend: local
    storageClass: ""
    path: /tmp/tempo

  querier:
    frontend_address: 127.0.0.1:9095

  query_frontend:
    search_enabled: true

  # Mount generated ConfigMap
  extraArgs:
    - "--config.file=/conf/tempo.yaml"

  extraVolumeMounts:
    - name: tempo-config
      mountPath: /conf

  extraVolumes:
    - name: tempo-config
      configMap:
        name: tempo-config

#tempo:
#  service:
#    type: ClusterIP
#    ports:
#      - name: otlp-grpc
#        port: 4317
#        targetPort: 4317
#      - name: otlp-http
#        port: 4318
#        targetPort: 4318
#      - name: tempo
#        port: 3200
#        targetPort: 3200
#
#  resources:
#    requests:
#      memory: 1.5Gi
#      cpu: 250m
#    limits:
#      memory: 2Gi
#      cpu: 500m
#
#  persistence:
#    enabled: false
#
#  metricsGenerator:
#    enabled: false
#
#  config:
#    server:
#      http_listen_port: 3200
#      grpc_listen_port: 9095
#
#    distributor:
#      receivers:
#        otlp:
#          protocols:
#            grpc: {}
#            http: {}
#
#    ingester:
#      trace_idle_period: 10s
#      max_block_duration: 5m
#
#    compactor:
#      compaction:
#        block_retention: 1h
#
#    storage:
#      trace:
#        backend: local
#        local:
#          path: /tmp/tempo
#
#    querier:
#      frontend_worker:
#        frontend_address: 127.0.0.1:9095
#
#    query_frontend:
#      search:
#        enabled: true
