tempo:
  enabled: true
  service:
    # existing config...
  resources:
    # existing config...
  persistence:
    enabled: false

  # === ⚙️ Enable trace-derived metrics ===
  metricsGenerator:
    enabled: true
    remoteWriteUrl: "http://thanos-receiver-receive.thanos-ns.svc.cluster.local:19291/api/v1/write"

  # === (Optional) Override processors to include service-graphs, span-metrics, local-blocks ===
  overrides:
    defaults:
      metrics_generator:
        processors:
          - service-graphs
          - span-metrics
          - local-blocks

  # All your existing config continues below...
  server:
    http_listen_port: 3200
    grpc_listen_port: 9095
  ingester:
    trace_idle_period: "10s"
    max_block_duration: "5m"
  compactor:
    block_retention: "1h"
  storage:
    backend: local
    path: /tmp/tempo
  querier:
    frontend_address: 127.0.0.1:9095
  query_frontend:
    search_enabled: true
  extraArgs:
    - "--config.file=/conf/tempo.yaml"
  extraVolumes:
    - name: tempo-config
      configMap:
        name: tempo-config
  extraVolumeMounts:
    - name: tempo-config
      mountPath: /conf
