apiVersion: v1
kind: Service
metadata:
  name: {{ include "otel-collector.fullname" . }}-{{ .Values.metricsService.nameSuffix | default "metrics-generation" }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "otel-collector.labels" . | nindent 4 }}
spec:
  type: {{ .Values.metricsService.type | default "ClusterIP" }}
  selector:
    {{- range $key, $value := .Values.metricsService.selectorLabels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  ports:
    - name: {{ .Values.metricsService.port.name | default "red-metrics" }}
      port: {{ .Values.metricsService.port.port | default 8889 }}
      targetPort: {{ .Values.metricsService.port.targetPort | default 8889 }}
      protocol: {{ .Values.metricsService.port.protocol | default "TCP" }}
