apiVersion: v1
kind: Service
metadata:
  name: otel-collector-metrics-generation
  namespace: otel-ns
  labels:
    app.kubernetes.io/name: opentelemetry-collector
    app.kubernetes.io/instance: otel-collector
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: opentelemetry-collector
    app.kubernetes.io/instance: otel-collector
  ports:
    - name: red-metrics
      port: 8889
      targetPort: 8889
      protocol: TCP
