apiVersion: v1
kind: Service
metadata:
  name: {{ include "otel-collector.fullname" . }}-metrics-generation
  labels:
    app.kubernetes.io/name: {{ include "otel-collector.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "otel-collector.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: prometheus-metrics
      protocol: TCP
      port: 8889
      targetPort: 8889
