# app-gitops-manifests-repo/platform-apps/otel-config/instrumentation.yaml

apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  # Using the name defined for the Instrumentation CR
  name: flask-app-instrumentation
  namespace: "flask-app-ns"
spec:
  exporter:
    # The collector endpoint
    endpoint: http://otel-collector-opentelemetry-collector.otel-ns.svc.cluster.local:4317

  python:
    volumeClaimTemplate: {}
    env:
      # Environment variables for the injected Python agent
      - name: OTEL_PYTHON_AUTOLOAD_ENABLED
        value: "true"
      - name: OTEL_METRICS_EXPORTER
        value: "otlp"
      - name: OTEL_LOGS_EXPORTER
        value: "otlp"
      - name: OTEL_TRACES_EXPORTER
        value: "otlp"
      - name: OTEL_PROPAGATORS
        value: "tracecontext,baggage"
      - name: OTEL_SERVICE_NAME
        value: "flask-app"
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: "http://otel-collector-opentelemetry-collector.otel-ns.svc.cluster.local:4317"
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: "grpc"
      - name: OTEL_RESOURCE_ATTRIBUTES
        value: "deployment.environment=k8s"