apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: flask-app-instrumentation
  namespace: flask-app-ns
spec:
  selector:
    matchLabels: # Important for Auto-injection of OTEL_ env vars
      app.kubernetes.io/instance: flask-app
  exporter:
    endpoint: "http://otel-collector-opentelemetry-collector.otel-ns.svc.cluster.local:4317"
  python:
    volumeClaimTemplate: {}
    env:
      - name: OTEL_PYTHON_AUTOLOAD_ENABLED
        value: "true"
      - name: OTEL_PYTHON_AUTO_ENABLE_METRICS
        value: "true"
      - name: OTEL_METRICS_EXPORTER
        value: "otlp"
      - name: OTEL_LOGS_EXPORTER
        value: "otlp"
      - name: OTEL_TRACES_EXPORTER
        value: "otlp"
      - name: OTEL_PROPAGATORS
        value: "tracecontext,baggage"
      - name: OTEL_SERVICE_NAME
        value: "flask-app"
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: "http://otel-collector-opentelemetry-collector.otel-ns.svc.cluster.local:4317"
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: "grpc"
      - name: OTEL_RESOURCE_ATTRIBUTES
        value: "deployment.environment=k8s"
      - name: OTEL_LOG_LEVEL
        value: "DEBUG"  # or INFO or WARN; controls output verbosity
      - name: OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED
        value: "true"
