{{- if .Values.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: flask-simulator
spec:
  schedule: {{ .Values.interval | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: curl
              image: curlimages/curl:latest
              command: ["/bin/sh"]
              args:
                - -c
                - |
                  {{- range .Values.endpoints }}
                  curl -s http://flask-app.flask-app-ns.svc.cluster.local:5000{{ .path }} || true
                  {{- end }}
          restartPolicy: OnFailure
{{- end }}
