apiVersion: v2
name: thanos-query-app
version: 0.1.0
appVersion: "0.39.1"
description: Thanos Query app managed by ArgoCD with exemplars support
type: application

home: https://thanos.io/
sources:
  - https://github.com/bitnami/charts/tree/main/bitnami/thanos

dependencies:
  - name: thanos
    version: "17.2.3"
#    repository: "https://charts.bitnami.com/bitnami"
    repository: "oci://registry-1.docker.io/bitnamicharts"
    alias: query