loki:
  singleBinary:
    replicas: 1
    podSecurityContext:
      fsGroup: 10001
    securityContext:
      runAsUser: 10001
      runAsGroup: 10001

  storage:
    backend: filesystem
    bucketNames:
      chunks: "chunks"
      index: "index"
      wal: "wal"

  persistence:
    enabled: true
    size: 10Gi
    storageClassName: local-path

  auth_enabled: true

  commonConfig:
    path_prefix: /var/loki
    replication_factor: 1

  server:
    grpc_listen_port: 9095
    http_listen_port: 3100

  memberlistConfig:
    join_members:
      - loki-memberlist

  schemaConfig:
    configs:
      - from: "2020-10-24"
        store: boltdb-shipper
        object_store: filesystem
        schema: v11
        index:
          prefix: index_
          period: 24h

  storageConfig:
    boltdb_shipper:
      active_index_directory: /var/loki/index
      cache_location: /var/loki/boltdb-cache
      shared_store: filesystem
    filesystem:
      directory: /var/loki/chunks

  limits_config:
    max_entries_limit_per_query: 5000
    reject_old_samples: true
    reject_old_samples_max_age: 168h
    split_queries_by_interval: 15m

compactor:
  storage:
    type: filesystem

ruler:
  storage:
    type: filesystem
