main:
  loki:
    auth_enabled: true
    commonConfig:
      path_prefix: /var/loki
      replication_factor: 1

    server:
      grpc_listen_port: 9095
      http_listen_port: 3100

    memberlistConfig:
      join_members:
        - loki-memberlist

    schemaConfig:
      configs:
        - from: "2020-10-24"
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h

    storage_config:
      boltdb_shipper:
        active_index_directory: /var/loki/index
        cache_location: /var/loki/boltdb-cache
        shared_store: filesystem
      filesystem:
        directory: /var/loki/chunks

    limits_config:
      max_entries_limit_per_query: 5000
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      split_queries_by_interval: 15m

