loki:
  commonConfig:
    replication_factor: 1
  storage:
    type: 'filesystem'
    bucketNames:
      chunks: chunks
      ruler: ruler
      admin: admin
  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  storage_config:
    filesystem:
      directory: /tmp/loki/chunks
  pattern_ingester:
    enabled: true
  limits_config:
    allow_structured_metadata: true
    volume_enabled: true
  ruler:
    enable_api: true
  auth_enabled: false

minio:
  enabled: false

deploymentMode: SingleBinary

singleBinary:
  replicas: 1
  persistence:
    storageClass: gp2
    accessModes:
      - ReadWriteOnce
    size: 20Gi

  resources:
    requests:
      cpu: "1"
      memory: "2Gi"
    limits:
      cpu: "2"
      memory: "4Gi"

backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0

chunksCache:
  allocatedMemory: 500

#loki:
#  singleBinary:
#    replicas: 1
#    podSecurityContext:
#      fsGroup: 10001
#    securityContext:
#      runAsUser: 10001
#      runAsGroup: 10001
#
#  storage:
#    backend: filesystem
#    bucketNames:
#      chunks: "chunks"
#      index: "index"
#      wal: "wal"
#
#  persistence:
#    enabled: true
#    size: 10Gi
#    storageClassName: local-path
#
#  auth_enabled: true
#
#  commonConfig:
#    path_prefix: /var/loki
#    replication_factor: 1
#
#  server:
#    grpc_listen_port: 9095
#    http_listen_port: 3100
#
#  memberlistConfig:
#    join_members:
#      - loki-memberlist
#
#  schemaConfig:
#    configs:
#      - from: "2020-10-24"
#        store: boltdb-shipper
#        object_store: filesystem
#        schema: v11
#        index:
#          prefix: index_
#          period: 24h
#
#  storageConfig:
#    boltdb_shipper:
#      active_index_directory: /var/loki/index
#      cache_location: /var/loki/boltdb-cache
#      shared_store: filesystem
#    filesystem:
#      directory: /var/loki/chunks
#
#  limits_config:
#    max_entries_limit_per_query: 5000
#    reject_old_samples: true
#    reject_old_samples_max_age: 168h
#    split_queries_by_interval: 15m
#
#  compactor:
#    storage:
#      type: filesystem
#
#  ruler:
#    storage:
#      type: filesystem
#
#  monitoring:
#    enabled: false
#    grafanaAgent:
#      enabled: false
#    serviceMonitor:
#      enabled: false
#    rules:
#      enabled: false
#    lokiCanary:
#      enabled: true

# Explicit top-level disabling of agent CRDs and workloads if present in chart
#grafana-agent-operator:
#  enabled: false
#
#grafana-agent:
#  enabled: false


#monitoring:
#  selfMonitoring:
#    enabled: false
#    grafanaAgent:
#      installOperator: false
#      enabled: false  # <-- important extra line
#  serviceMonitor:
#    enabled: false
#  rules:
#    enabled: false
#  dashboards:
#    enabled: false
#  lokiCanary:
#    enabled: false  # disables loki-canary side workload
#  lokiCanaryConfig:
#    enabled: false



# Explicit top-level disabling of agent CRDs and workloads if present in chart
#grafana-agent-operator:
#  enabled: false
#
#grafana-agent:
#  enabled: false
