# Force single binary deployment mode
deploymentMode: SingleBinary

loki:
  auth_enabled: false

  # Common configuration
  commonConfig:
    replication_factor: 1
    ring:
      kvstore:
        store: inmemory

  # Storage configuration with required bucketNames
  storage:
    type: filesystem
    bucketNames:
      chunks: "chunks"
      ruler: "ruler"
      admin: "admin"
    filesystem:
      chunks_directory: /var/loki/chunks
      rules_directory: /var/loki/rules

  # Schema configuration
  schemaConfig:
    configs:
      - from: "2020-10-24"
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: index_
          period: 24h

  # Storage config for filesystem backend
  storage_config:
    filesystem:
      directory: /var/loki/chunks
    tsdb_shipper:
      active_index_directory: /var/loki/index
      cache_location: /var/loki/index_cache
      shared_store: filesystem

  # Limits configuration
  limits_config:
    retention_period: 744h
    enforce_metric_name: false
    reject_old_samples: true
    reject_old_samples_max_age: 168h
    max_cache_freshness_per_query: 10m
    split_queries_by_interval: 15m
    per_stream_rate_limit: 3MB
    per_stream_rate_limit_burst: 15MB
    ingestion_rate_mb: 4
    ingestion_burst_size_mb: 6
    max_streams_per_user: 10000
    max_line_size: 256000
    max_entries_limit_per_query: 5000
    max_global_streams_per_user: 5000
    unordered_writes: true
    max_chunks_per_query: 2000000
    max_query_length: 721h
    max_query_parallelism: 32
    max_query_series: 10000
    cardinality_limit: 100000
    max_streams_matchers_per_query: 1000
    max_concurrent_tail_requests: 10
    max_query_lookback: 30d
    min_sharding_lookback: 0s
    max_query_bytes_read: 1GB
    max_querier_bytes_read: 1GB
    volume_enabled: true

  # Server configuration
  server:
    http_listen_port: 3100
    grpc_listen_port: 9095
    log_level: info

  # Compactor configuration
  compactor:
    working_directory: /var/loki/compactor
    retention_enabled: true
    retention_delete_delay: 2h
    retention_delete_worker_count: 150
    delete_request_store: filesystem

  # Query configuration
  query_range:
    align_queries_with_step: true
    cache_results: false
    max_retries: 5
    parallelise_shardable_queries: true

  # Querier configuration
  querier:
    max_concurrent: 2048

  # Frontend configuration
  frontend:
    max_outstanding_per_tenant: 2048
    compress_responses: true
    log_queries_longer_than: 5s

  # Ingester configuration
  ingester:
    lifecycler:
      ring:
        kvstore:
          store: inmemory
        replication_factor: 1
    chunk_idle_period: 30m
    chunk_block_size: 262144
    chunk_encoding: snappy
    chunk_retain_period: 1m
    max_transfer_retries: 0
    wal:
      enabled: true
      dir: /var/loki/wal
      checkpoint_duration: 5m
      flush_on_shutdown: true
      replay_memory_ceiling: 4GB

  # Pattern ingester
  pattern_ingester:
    enabled: false

  # Tracing
  tracing:
    enabled: false

  # UI
  ui:
    enabled: false

# Single binary configuration
singleBinary:
  replicas: 1
  persistence:
    enabled: true
    size: 10Gi
    storageClass: local-path
  podSecurityContext:
    fsGroup: 10001
  securityContext:
    runAsUser: 10001
    runAsGroup: 10001
    readOnlyRootFilesystem: true
  resources:
    limits:
      cpu: 4
      memory: 8Gi
    requests:
      cpu: 1
      memory: 4Gi
  extraVolumes:
    - name: tmp
      emptyDir: {}
  extraVolumeMounts:
    - name: tmp
      mountPath: /tmp
  extraArgs:
    - -config.expand-env=true
    - -log.level=info

# Disable all distributed components
write:
  replicas: 0

read:
  replicas: 0

backend:
  replicas: 0

# Disable enterprise features
enterprise:
  enabled: false

# Disable caching
chunksCache:
  enabled: false

resultsCache:
  enabled: false

# Disable ruler
ruler:
  enabled: false

# Disable table manager
tableManager:
  retention_deletes_enabled: false

# Disable monitoring
monitoring:
  enabled: false

# Disable test pods
test:
  enabled: false

# Disable gateway
gateway:
  enabled: false

# Disable ingester
ingester:
  replicas: 0

# Disable querier
querier:
  replicas: 0

# Disable query frontend
queryFrontend:
  replicas: 0

# Disable distributor
distributor:
  replicas: 0

# Disable compactor
compactor:
  replicas: 0

# Disable index gateway
indexGateway:
  replicas: 0

# Global settings
global:
  clusterDomain: cluster.local