main:
  deploymentMode: SingleBinary

  singleBinary:
    replicas: 1

  simpleScalable:
    enabled: false
    gateway:
      replicas: 0
    distributor:
      replicas: 0
    ingester:
      replicas: 0
    querier:
      replicas: 0
    queryFrontend:
      replicas: 0
    compactor:
      replicas: 0
    ruler:
      replicas: 0
    indexGateway:
      replicas: 0
    bloomGateway:
      replicas: 0

  loki:
    auth_enabled: false
    storage:
      type: filesystem
      filesystem:
        directory: /var/loki

    schemaConfig:
      configs:
        - from: 2024-01-01
          store: boltdb-shipper
          object_store: filesystem
          schema: v13
          index:
            prefix: index_
            period: 24h

    compactor:
      working_directory: /var/loki/compactor
      shared_store: filesystem

    limits_config:
      retention_period: 168h

  persistence:
    enabled: true
    storageClassName: standard
    accessModes:
      - ReadWriteOnce
    size: 5Gi
