loki:
  singleBinary:
    replicas: 1
    podSecurityContext:
      fsGroup: 10001
    securityContext:
      runAsUser: 10001
      runAsGroup: 10001

  storage:
    backend: filesystem
    bucketNames:
      chunks: "chunks"
      index: "index"
      wal: "wal"

  persistence:
    enabled: true
    size: 10Gi
    storageClassName: local-path

  auth_enabled: true

  commonConfig:
    path_prefix: /var/loki
    replication_factor: 1

  server:
    grpc_listen_port: 9095
    http_listen_port: 3100

  memberlistConfig:
    join_members:
      - loki-memberlist

  schemaConfig:
    configs:
      - from: "2020-10-24"
        store: boltdb-shipper
        object_store: filesystem
        schema: v11
        index:
          prefix: index_
          period: 24h

  storageConfig:
    boltdb_shipper:
      active_index_directory: /var/loki/index
      cache_location: /var/loki/boltdb-cache
      shared_store: filesystem
    filesystem:
      directory: /var/loki/chunks

  limits_config:
    max_entries_limit_per_query: 5000
    reject_old_samples: true
    reject_old_samples_max_age: 168h
    split_queries_by_interval: 15m

  compactor:
    storage:
      type: filesystem

  ruler:
    storage:
      type: filesystem

  monitoring:
    enabled: false
    grafanaAgent:
      enabled: false
    serviceMonitor:
      enabled: false
    rules:
      enabled: false
    lokiCanary:
      enabled: false

    # Test pods that might include agent
    test:
      enabled: false

  selfMonitoring:
    enabled: false
    grafanaAgent:
      installOperator: false
      enabled: false

# Explicit top-level disabling of agent CRDs and workloads if present in chart
grafana-agent-operator:
  enabled: false

grafana-agent:
  enabled: false

# Top-level disables for various agent components
# Try these if the above doesn't work
grafana-agent-operator:
  enabled: false

grafana-agent:
  enabled: false

# Alternative naming patterns that might be used
grafanaAgent:
  enabled: false

grafana_agent:
  enabled: false

# Sometimes it's under global monitoring settings
global:
  monitoring:
    enabled: false

# Or under a monitoring section at root level
monitoring:
  enabled: false
  grafanaAgent:
    enabled: false


#monitoring:
#  selfMonitoring:
#    enabled: false
#    grafanaAgent:
#      installOperator: false
#      enabled: false  # <-- important extra line
#  serviceMonitor:
#    enabled: false
#  rules:
#    enabled: false
#  dashboards:
#    enabled: false
#  lokiCanary:
#    enabled: false  # disables loki-canary side workload
#  lokiCanaryConfig:
#    enabled: false



# Explicit top-level disabling of agent CRDs and workloads if present in chart
#grafana-agent-operator:
#  enabled: false
#
#grafana-agent:
#  enabled: false
