# Minimal configuration to avoid template errors
loki:
  auth_enabled: false

  commonConfig:
    replication_factor: 1

  storage:
    bucketNames:
      chunks: "chunks"
      ruler: "ruler"
      admin: "admin"
    type: filesystem

  schemaConfig:
    configs:
      - from: "2020-10-24"
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: index_
          period: 24h

singleBinary:
  replicas: 1
  persistence:
    enabled: true
    size: 10Gi
    storageClass: local-path

# Disable everything else
enterprise:
  enabled: false

chunksCache:
  enabled: false

resultsCache:
  enabled: false

ruler:
  enabled: false

tableManager:
  retention_deletes_enabled: false

monitoring:
  enabled: false

test:
  enabled: false

gateway:
  enabled: false