---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: thanos-ns
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgBjSdgxOhAm8khgfCZSzEs9h4gDXmKOWWSQHOFk1YUp4Du1Jm+Tu4vx2ad0Jy+vM55457+WI2lJ4xSUpLngqd1SXtIfU90BuKjJpdHC1JlauSjHhcSt/2YNtNI2SZJd/nig/cACv0j6HDUo8lCFn8MEB6jflEbXm30eAhU7opRlHiye0nvvQAqS3znKksmdgzQRDcNIVsVEJk4r/Tof9J6fxAs5oQDCtxXxiSQ7ZDkQgr4H2l3cogSOvXyt3ppICTNO8og43YR1oTZ7gWPQ3tEiT4F4oRsBaBPRWNTj3USccbUmGvSc/3Eh+BA0tIjdlFMoCJ+WkndOU+rZTf2PiMqOCjZPCYYJ7kju5QB0C4lyZZHw0/Ih5Vh95mUXxafO+5DYOZe2eZ0BvxWcsRKqDCNuzP20uMN01WuMlR/IQuDrQNAXTuvotmPPJullFVTV/mC51bzl5uuG43xJM9Ngx1aNTQTR5T3sKshqpa0976liXpFZuhGhfYKe/a5GZPItcksde38NZR9UNP/IHDgEaQYkRs7lS2N7gfZofE/Ta93grXSk38uFqu/GzyU95qixkXLfiXXBeZpB0EwyJjbzt7H48x3ScWd8vmhuMGvsmhj61Rt3DQ+H8YWvzG2Bgt2QMu79aFvsksMK1j6U/XiLJFPZLN0efiDCJXqgGe3NYwPzD7GSRjcdWxn/fDN8+1N5GxUJqXXXGoo5VWpD4xNe2v1AfhBZMQ==
    AWS_SECRET_ACCESS_KEY: AgBrD7NrZo6fKOWIJiarK3JqLHEdJ1m/54SLokhGp+Wa3MC3cyWx9DAd0MLB9G6ggPfkCTy0TDoyim6/9x/C+9t0Np23uo01P98k1ZYCoopw8cSQeuKMQeLtD7xdnr963fLOpE2rEqZy0qD2hRTq4zGhoTWFsrNMH85cvsuoUnlpF1Z/h7mLmuxVE/sofZEBXtoUeEYfszW8WskKiKcihZdcZu9QAsCFDonOMiO80iJHRgAFc5LOxuxvZX0gxZW12l2z/q5IVzQG1UTazazTnt0ehF/pWnAev+wXQOJFyE5LmNAimC4QwckcGkTLdVhiHvMZkc/LtsdWDM+DvA/YazEBk3QZocjT02wKWeenqDx7GPznidup0RrZ8zvMpQtWqwQXQgF8WnauApqRgZFKTzReJSPgF8O+CT4VCU1YcAaElb6eMqi77w5tNsVaiBXhzavuVL5+dLLvTgbwFhCbnURzcnVOfEnNvdOSAWm6NNAQb6MgzPwiHlCKYbhCOgQuQNQI88zORRc7NuQnl4PlF2GMJ2W1l/lJaDwd7ebDvneULZ1H160Imjj2ktveBZOvpMtE+aRLLtD5gnHQKlFUXDC2BIYsWElY3JLrzmw5RFT5jwRKvuyN2mLjfc4vV3nYfkVuOtrifHtaGb0OSdotE7LRpMP+t+QCATmEINuER5uuueebIvX7rUlLTPJWveWVG2FAg3hC7INgpe5zeZ5V1JjBw1lrXiDUI7d2gjVPdC0JmftcmZKauZBJ
  template:
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: thanos-ns
    type: Opaque
