# app-gitops-manifests-repo/platform-apps/thanos-receiver/values.yaml

queryFrontend:
  enabled: false

receive:
  enabled: true
  service:
    type: ClusterIP
    ports:
      remote: 19291
      grpc: 10901
  ingress:
    enabled: false
  autoscaling:
    enabled: false
  containerPorts: # These are the ports the container directly exposes
    grpc: 10901
    http: 10902 # Common to have an HTTP port as well
    remote: 19291 # Matches your remote write port

storegateway:
  ingress:
    enabled: false
    grpc:
      enabled: false

ruler:
  enabled: false
  ingress:
    enabled: false