# app-gitops-manifests-repo/platform-apps/thanos-receiver/values.yaml

queryFrontend:
  enabled: false

receive:
  enabled: true
  service:
    type: ClusterIP
    ports:
      remote: 19291
      grpc: 10901
  ingress:
    enabled: false # Even if 'receive' is enabled, its ingress is not

storegateway:
  ingress:
    enabled: false
    grpc:
      enabled: false

ruler:
  enabled: false
  ingress:
    enabled: false