apiVersion: v1
kind: ConfigMap
metadata:
  name: thanos-objstore-config
  namespace: {{ .Values.receiver.global.namespace }}
  labels:
    {{- include "thanos-receiver-app.labels" . | nindent 4 }}
data:
  objstore.yml: |-
{{ .Values.receiver.objstoreConfig | nindent 4 }}