apiVersion: v1
kind: Secret
metadata:
  name: thanos-objstore-config
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  objstore.yml: |-
    type: S3
    config:
      bucket: "alkon-thanos-metrics-dev"
      endpoint: "s3.us-east-1.amazonaws.com"
      region: "us-east-1"
      aws_sdk_auth: true