apiVersion: v1
kind: ConfigMap
metadata:
  name: thanos-scrape-config
  namespace: monitoring
data:
  prometheus.yaml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: otel-spanmetrics
        static_configs:
          - targets:
              - otel-collector.monitoring.svc.cluster.local:8889
